### PR TITLE
Fix follow/unfollow/this is you button not showing

### LINKED ISSUE #39: Fix follow button not being visible

### PR DESCRIPTION
**Pull request by Herover**
Closes #39 but currently there's still locked db issues.

### CODE REVIEW

**Comment by smilladion** [comment]
This change seems to have completely removed the ability to post a message? Before I could do so after signing up or logging in, although if I went away from the page then I had to log out before I could post messages again.

Testing this with a database which already has messages, it seems to work - but it's hard to test it properly with the locked DB errors, so perhaps we need to merge that first.

**Comment by Herover** [comment]
Fixed the template issue @smilladion, I think posting messages works as well if the user manually go to the / page?

**Comment by Herover** [comment]
Just realized this also fixes #30 that was already assigned to @pizzaluc, I hope its ok

**Review by smilladion — APPROVED** [review]
It works wonderfully now! Seems like it actually also fixes #60? Maybe before merging you should add that issue, and the one you just mentioned, to the PR so that they get moved. :P All we need now is to merge this with `fix-invis-message-input`, and I think we are done with the bugs.

**Pull request merged**
