### PR TITLE
Add error catcher that logs route errors

### PR DESCRIPTION
**Pull request by Herover**
Prints caught errors to terminal and show simple error to user.

### CODE REVIEW

**Review by pizzaluc — APPROVED** [review]
Looks pretty good to me, at some point this should probably be logged in a file instead

**Review by smilladion — APPROVED** [review]
Lots of line changes in this one, so kind of hard to see the exact changes, but from what I can see it seems you simply got rid of all the internal try-catch blocks for the routes and made an outer method for error handling instead. Seems fine to me! Only thing to consider is whether there are any exceptions where we want to handle different logic than simply printing it. But I don't think that's the case right now.

**Review by erentomurcuk — APPROVED** [review]
I agree with logging, can be added later on. Otherwise than that, it looks good to me too!

**Comment by Herover** [comment]
I have opinions about the logging comments but lets take that later :D

**Pull request merged**
