### PR TITLE
Add msgs api endpoint + utilities

### PR DESCRIPTION
**Pull request by Herover**
* Adds a common "path" to add sim API endpoints
* Adds basic auth protection on API endpoints
* Adds gson by google dependency for easy JSON encoding
* Move code for fetching public timeline content into own method

Consider if we should just move it directly into it's own class that can work as a independent server seperate from the WebApplication class, and perhaps create a new class for all the common functions. It's pretty easy right now and I think we might get it as a task later around 29/3.

### CODE REVIEW

**Review by pizzaluc — APPROVED** [review]
Honestly looks really clean, I have no comments.

**Review by smilladion — APPROVED** [review]
Looks very nice. I like the idea of using /api as a common path, however I thought the point was that their simulator is looking for specific routes to use? So their simulator is expecting us to have /msgs and not /api/msgs.

I also like the suggestion of moving it into a separate class. The more separation the better, I should think. But maybe it shouldn't be the focus yet.

**Comment by Herover** [comment]
I haven't exactly tested the sim, but as I read the code we just have to tell them that the app url is something like `http://ip:port` and the api url is `http://ip:port/api` as they just append paths to the "base" url, and the sim will be fine with it. But I guess its something we should test before handing in :D

**Comment by smilladion** [comment]
That makes sense! Hopefully it's possible. If not we can just create a new issue. So I think merging now is fine, unless someone else wants to take a look as well. :)

**Pull request merged**
