### PR TITLE
Add title tag values

### LINKED ISSUE #20: Port jinja blocks to velocity equivalent
Here https://github.com/Herover/itu-devops-h/blob/dev/minitwit/src/main/resources/templates/layout.vm#L3 a jinja block is used to get title from ex. https://github.com/Herover/itu-devops-h/blob/dev/minitwit/src/main/resources/templates/register.vm#L3. Can/should this be ported? We can just put a `title` value into the view model and define it in code instead of child templates.
Maybe [macros](https://velocity.apache.org/engine/1.7/user-guide.html#velocimacros) can do it.

### PR DESCRIPTION
**Pull request by Herover**
Closes #20

### CODE REVIEW

**Review by smilladion — CHANGES_REQUESTED** [review]
Looks good, just a few things for the sake of nitpicking:
- "Public timeline" should be "Public Timeline"
- "Sign in" should be "Sign In"
- There seems to be a random gap between the title and the navbar, see picture (ours on the left, Python version on the right).

Capture

**Comment by Herover** [comment]
I fixed the spelling, the gab is because the placeholder for "splash"-es was buggy, we should probably consider looking into those at some point as well. I don't think there's a issue for them right now :/

**Comment by smilladion** [comment]
> 

Ah right, looks fixed now. Although sign up/sign in pages still have a gap. Honestly it's so minor I doubt that it's important, up to you whether you want to fix it! I'll approve.

**Review by smilladion — APPROVED** [review]

**Comment by Herover** [comment]
On a second thought it's probably not really related to this PRs topic but it looks annoying did a quickfix :D

**Pull request merged**
